version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: whatsapp_db
    environment:
      POSTGRES_USER: whatsapp
      POSTGRES_PASSWORD: whatsapp123
      POSTGRES_DB: whatsapp_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - whatsapp_network

  redis:
    image: redis:7-alpine
    container_name: whatsapp_redis
    ports:
      - "6379:6379"
    networks:
      - whatsapp_network

  backend:
    build: ./backend
    container_name: whatsapp_backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://whatsapp:whatsapp123@postgres:5432/whatsapp_system
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 3001
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - whatsapp_network

  frontend:
    build: ./frontend
    container_name: whatsapp_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_WS_URL: ws://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - whatsapp_network

volumes:
  postgres_data:

networks:
  whatsapp_network:
    driver: bridge
