[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npm run build"]

[start]
cmd = "cd backend && npx prisma migrate deploy && npm start"
